### PR TITLE
change to "pick an item of clothing" and appathetic

### PR DESCRIPTION
**Pull request by CrisGavril**
change to "pick an item of clothing"
appathetic misspelling

### CODE REVIEW

**Comment by Machinewarlock** [comment]
This is good. Merging.

**Comment by aliblackwell** [comment]
fixes #85

**Comment by aliblackwell** [comment]
@CrisGavril still a tiny typo on line 33

also remove spaces around equals signs

**Comment by Machinewarlock** [comment]
Fixed https://github.com/bridgeatwaterloo/david/pull/102

**Pull request merged**
